/**
 * Communication.js
 * Handles WebRTC P2P communication using PeerJS.
 * 
 * Usage:
 * - A QR code generated by the Main UI contains the URL to this app, appending `?peerId=MAIN_UI_ID`.
 * - This app connects to that ID to stream the final data directly.
 */

class Communicator {
    constructor() {
        this.peer = null;
        this.conn = null;
        this.mainUiPeerId = this._getPeerIdFromUrl();
        this.statusCallback = null;
    }

    _getPeerIdFromUrl() {
        const urlParams = new URLSearchParams(window.location.search);
        return urlParams.get('peerId');
    }

    onStatusChange(callback) {
        this.statusCallback = callback;
    }

    _updateStatus(status, message) {
        if (this.statusCallback) {
            this.statusCallback(status, message);
        }
    }

    init() {
        if (!this.mainUiPeerId) {
            console.warn("No peerId found in URL. Running in standalone mode.");
            this._updateStatus('standalone', 'Standalone Mode (No Main UI)');
            return;
        }

        this._updateStatus('connecting', 'Connecting to Main UI...');
        
        // Initialize PeerJS
        this.peer = new Peer();

        this.peer.on('open', (id) => {
            console.log('My peer ID is: ' + id);
            this._connectToMainUi();
        });

        this.peer.on('error', (err) => {
            console.error('PeerJS error:', err);
            this._updateStatus('error', 'Connection Error');
        });
    }

    _connectToMainUi() {
        this.conn = this.peer.connect(this.mainUiPeerId, {
            reliable: true
        });

        this.conn.on('open', () => {
            console.log('Connected to Main UI');
            this._updateStatus('connected', 'Connected');
            
            // Notify Main UI we are ready
            this.conn.send({ type: 'MOBILE_APP_READY' });
        });

        this.conn.on('close', () => {
            this._updateStatus('error', 'Disconnected');
        });
    }

    sendPayload(svgContent, imageUrl, meta) {
        if (!this.conn || !this.conn.open) {
            console.warn("Not connected to Main UI. Cannot send payload.");
            // We can download it manually if standalone
            return false;
        }

        try {
            this.conn.send({
                type: 'PROCESSING_COMPLETE',
                payload: {
                    svg: svgContent,
                    image: imageUrl,
                    dots_per_mm: meta?.dots_per_mm,
                    physical_width: meta?.physical_width,
                    physical_height: meta?.physical_height
                }
            });
            console.log("Payload sent successfully to Main UI.");
            return true;
        } catch (e) {
            console.error("Failed to send payload:", e);
            return false;
        }
    }
}

window.Communicator = Communicator;
